services:
  backend:
    container_name: convex-backend
    restart: unless-stopped
    image: ghcr.io/get-convex/convex-backend:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    env_file:
      - .env
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s

    networks:
      - convex-network

  dashboard:
    container_name: convex-dashboard
    image: ghcr.io/get-convex/convex-dashboard:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:${PORT:-3210}}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - convex-network

volumes:
  data:

networks:
  convex-network:
    driver: bridge